### ISSUE TITLE
chore(web): better documentation re Web's setKeyboardForControl

### ISSUE THREAD

**Issue by jahorton** [keymanapp/help.keyman.com#1037]
From a user:

> The only thing I have not been able to work out is how to call setKeyboardForControl() with language codes rather than keyboard ID, since if keyboards are added using language codes, it is clearly safer to use language codes rather than keyboard IDs for calling setKeyboardForControl().  I could find no accepted syntax or way of using either two or three letter language codes rather than the internal names. It is either a bug or a documentation issue.
>
> The solution I have now implemented is to list the loaded keyboards and get the internal name for each requested language code:
>
> ```
> const kbds = keyman.getKeyboards();
> let i=0,thID=null,laID=null;
> for(i=0; i<kbds.length; i++) {
> if(!thID && kbds[i].LanguageCode == 'th') thID = kbds[i].InternalName;
>   if(!laID && kbds[i].LanguageCode == 'lo') laID = kbds[i].InternalName;
> }
> if(pt) {keyman.attachToControl(pt); keyman.setKeyboardForControl(pt,thID);}
> if(pl) {keyman.attachToControl(pl); keyman.setKeyboardForControl(pl,laID);}
> if(ps) {keyman.attachToControl(ps); keyman.setKeyboardForControl(ps,thID);}                
> ```
>           
> And that worked.

Compare against https://help.keyman.com/developer/engine/web/17.0/reference/core/setKeyboardForControl.

It's quite up-front about using a keyboard's internal name.  The issue, as I see it - the fact that both `keyboard` and `languageCode` are optional led this user to infer that _either_ one _or_ the other would be sufficient to specify a keyboard - not that it was a "both" or "neither" situation.  (Technically, only the first is needed, but then language tagging might be off.)

While we don't yet activate predictive text in standalone web, the "both" or "neither" distinction will matter to users if we ever do add infrastructure for distributing lexical models via cloud for KMW use - the language code must be accurate in order for a matching model to activate, even within the mobile apps, after all.

Also, it would be wise to have that help (reference) page link the following help (guide) page: https://help.keyman.com/developer/engine/web/17.0/guide/examples/control-by-control

**Comment by darcywong00** [comment]
Assigning to @jahorton - but likely will be A18S1 before he's available
