### ISSUE TITLE
docs(windows): add missing command line switches to kmshell kb article 98 

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/help.keyman.com#1054]
More switches have been added to kmshell and the documentation needs to be updated to match.
The main missing one is 
`-ikl`

@mcdurdin  There are quite a few looking at initprop.pas. However, some I believe are for internal use some are soon to be depricated and the rest I am not sure about. Can you review these. 
Here is the list I have picked out
ikl
startwithconfiguration
splash
showhelp
settings
a

not sure about these. Also I will need to learn how to use them :)
upgradekeyboards
disablepackages
defaultuilanguage
upgrademnemoniclayout
kw
kp
log

Don't seem to work
-nowelcome
-?

All the rest I believe are for internal use only such as
ukl
ra
rr
basekeyboard
repair

**Comment by mcdurdin** [comment]
I think we should document them all, and note which ones are for internal use. That will help us -- given you currently don't know how they all work and I've forgotten too :grin:

**Comment by rc-swag** [comment]
I have created a new issue for cleaning up the code around switches that are no longer valid and don't work. #10855

**Comment by rc-swag** [comment]
fixed by https://github.com/keymanapp/help.keyman.com/pull/1064
