### ISSUE TITLE
feat: use new history files for 14.0+ history

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#106]
History will be now stored in https://downloads.keyman.com/history/HISTORY.md. Just the one file. The format of the file, is approximately:

```
# Keyman Version History

## <version> <tier> <yyyy-mm-dd>
<type>[(<scope>[/<sub-scope>)]: title [(#<prnum>)]
```

For example:

```
# Keyman Version History

## 14.0.4 alpha 2020-02-03

chore(ci): trigger builds after version increment (#2572)
```

We need to parse this for presenting history to users for version 14.0 and later. A single history view covering all platforms is appropriate -- sort the entries by scope to make it easier to read.

**Comment by darcywong00** [comment]
Fixed in `staging` by #262
