### ISSUE TITLE
chore: convert Developer 17.0 pages from PHP to MD

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#1088]
The following pages under /developer/17.0 are still in PHP:

- [x] `context/messages.php`
- [x] `context/model-editor.php`
- [x] `context/new-lm-project-parameters.php`
- [x] `context/new-project-parameters.php`
- [x] `context/new-project.php`
- [x] `context/new.php`
- [x] `context/options.php`
- [x] `context/project.php`
- [x] `context/startup.php`
- [x] `guides/develop/advanced-keyboard-development-example.php`
- [x] `guides/develop/creating-a-touch-keyboard-layout-for-amharic.php`
- [x] `guides/develop/imx/imxdll.php`
- [x] `guides/develop/imx/imxlib.php`
- [x] `guides/develop/imx/index.php`
- [x] `guides/develop/imx/web.php`
- [x] `guides/develop/index.php`
- [x] `guides/develop/tutorial/index.php`
- [x] `guides/develop/tutorial/step-1.php`
- [x] `guides/develop/tutorial/step-2.php`
- [x] `guides/develop/tutorial/step-3.php`
- [x] `guides/develop/tutorial/step-4.php`
- [x] `guides/develop/tutorial/step-5.php`
- [x] `guides/develop/tutorial/step-6.php`
- [x] `guides/develop/tutorial/step-7.php`
- [x] `guides/develop/tutorial/step-8.php`
- [x] `guides/develop/tutorial/step-9.php`
- [x] `guides/distribute/index.php`
- [x] `guides/distribute/install-kmp-android.php`
- [x] `guides/distribute/install-kmp-ios.php`
- [x] `guides/distribute/packages.php`
- [x] `guides/distribute/tutorial/index.php`
- [x] `guides/distribute/tutorial/step-1.php`
- [x] `guides/distribute/tutorial/step-2.php`
- [x] `guides/distribute/tutorial/step-3.php`
- [x] `guides/distribute/tutorial/step-4.php`
- [x] `guides/distribute/tutorial/step-5.php`
- [x] `guides/distribute/tutorial/step-6.php`
- [x] `guides/index.php`
- [x] `guides/intro.php`
- [x] `guides/lexical-models/advanced/index.php`
- [x] `guides/lexical-models/advanced/model-definition-file.php`
- [x] `guides/lexical-models/advanced/punctuation.php`
- [x] `guides/lexical-models/advanced/search-term-to-key.php`
- [x] `guides/lexical-models/advanced/word-breaker.php`
- [x] `guides/lexical-models/distribute/index.php`
- [x] `guides/lexical-models/distribute/packages.php`
- [x] `guides/lexical-models/distribute/tutorial/index.php`
- [x] `guides/lexical-models/distribute/tutorial/step-1.php`
- [x] `guides/lexical-models/distribute/tutorial/step-2.php`
- [x] `guides/lexical-models/distribute/tutorial/step-3.php`
- [x] `guides/lexical-models/distribute/tutorial/step-4.php`
- [x] `guides/lexical-models/distribute/tutorial/step-5.php`
- [x] `guides/lexical-models/index.php`
- [x] `guides/lexical-models/intro/index.php`
- [x] `guides/lexical-models/tutorial/index.php`
- [x] `guides/lexical-models/tutorial/step-1.php`
- [x] `guides/lexical-models/tutorial/step-2.php`
- [x] `guides/lexical-models/tutorial/step-3.php`
- [x] `guides/lexical-models/tutorial/step-4.php`
- [x] `guides/web/guide_kmw_automatic_control.php`
- [x] `guides/web/guide_kmw_automatic_control_loaded.php`
- [x] `guides/web/guide_kmw_control_by_control.php`
- [x] `guides/web/guide_kmw_defaults.php`
- [x] `guides/web/guide_kmw_full_manual_control.php`
- [x] `guides/web/guide_kmw_manual_control.php`
- [x] `index.php`
- [x] `reference/editor-themes.php`
- [x] `reference/errors/index.php`

**Comment by Meng-Heng** [comment]
Hello @mcdurdin,
This is the code for `reference/errors/index.php`

```php
<?php
require_once('includes/util.php');
util_loadpage('../messages');
```

I will keep the PHP and not doing any conversion.

**Comment by mcdurdin** [comment]
> Hello @mcdurdin, This is the code for `reference/errors/index.php`
> 
> ```
> <?php
> require_once('includes/util.php');
> util_loadpage('../messages');
> ```

These can be converted into markdown too :grin:

The markdown header section has a keyword `redirect`, so then reference/errors/index.md would be:

```
---
redirect: ../messages
---
```

**Comment by Meng-Heng** [comment]
I should be able to close this issue now.
