### ISSUE TITLE
bug: Help files no longer have table of contents on the right

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/help.keyman.com#1143]
In the past the help files had a table of contents at the top right. That has now disappeared.

**Comment by LornaSIL** [comment]
Example page: https://help.keyman.com/keyboard/sil_ipa/1.8.7/sil_ipa

**Comment by mcdurdin** [comment]
It disappears if the page is too narrow. I am seeing it right now:

![image](https://github.com/keymanapp/help.keyman.com/assets/4498365/f3b0c9df-33ab-4422-a159-da435254b313)

**Comment by LornaSIL** [comment]
Interesting. Okay, I guess it can be closed if you wish!

**Comment by mcdurdin** [comment]
Closing :grin:
