### ISSUE TITLE
feat: Adding another good sample for https://keyman.com/developer/keymanweb/sample1

### ISSUE THREAD

**Issue by linuxguist** [keymanapp/help.keyman.com#1357]
### Is your feature request related to a problem? Please describe.

No

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Additional context

I would like to contribute the enclosed sample file, for the above mentioned subject location. Thanks.

[keymanweb.html.zip](https://github.com/user-attachments/files/15910734/keymanweb.html.zip)

**Comment by mcdurdin** [comment]
Note: moving this to help.keyman.com as the most appropriate location for now. It may end up on keyman.com if that makes sense.

**Comment by linuxguist** [comment]
Thank you very much. Yes, that would be great !
