### ISSUE TITLE
bug: allows lower-casing to URL searches 

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/help.keyman.com#1490]
I found out a lot of 404 pages from Google Console have `help.keyman.com/DEVELOPER/ENGINE/`, the developer lowercased but not everything that comes after, such as ENGINE, so Google identifies these as 404s.
For example:
![image](https://github.com/user-attachments/assets/06e30e06-f781-4b1f-a083-d1949e5f1ab2)

Please let me know if this is necessarily or not; though, I think it will help Google stop registering the ENGINE 404 pages.

FYI, there are approximately 5 ENGINE for every 10 URLs:
https://help.keyman.com/DEVELOPER/ENGINE/iphone-and-ipad/11.0/TextField/dismissKeyboard
https://help.keyman.com/DEVELOPER/ENGINE/WEB/2.0/reference/core/setActiveKeyboard
https://help.keyman.com/DEVELOPER/ENGINE/WEB/1.0/reference_kmw_Build
https://help.keyman.com/DEVELOPER/ENGINE/WEB/12.0/reference/osk

Issue: https://github.com/keymanapp/keyman.com/issues/415

**Comment by mcdurdin** [comment]
Yes, this is due to a bug in the old web server (IIS) which sometimes caused redirected pages to upper case. We could add canonicalization but it's quite a bit of work so I am not sure it is worthwhile to do?

**Comment by Meng-Heng** [comment]
Yes, then I won't prioritize this for now.
