### ISSUE TITLE
[help.keyman.com] Broken link to Android version history

### ISSUE THREAD

**Issue by sewhite** [keymanapp/help.keyman.com#15]
When I do a search on "kmea" I get two results. The second result is a page that does not exist,

![image](https://user-images.githubusercontent.com/16904461/42823546-d03ddc00-89ab-11e8-9a89-99ae4a0bbfc5.png)

The full URL for the missing page is:
https://help.keyman.com/products/android/10.0/version/?_ga=2.200103469.2034434210.1531837091-304870458.1501684319

**Comment by darcywong00** [comment]
The second search result now links to a valid page
https://help.keyman.com/products/android/version-history/
