### ISSUE TITLE
chore: iOS and Android apps are missing documentation on adding models

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#158]

**Comment by darcywong00** [comment]
Is this for adding models via the cloud vs custom packages?

Android help has [Installing Custom Keyboards/Dictionaries](https://help.keyman.com/products/android/13.0/installing-custom-packages)

**Comment by mcdurdin** [comment]
Yes, I noticed that the contextual is really totally missing for Settings. I think it's probably a gap in a lot of our product documentation -- we have 'how to' for a number of things, but no help for specific screens. So perhaps this would be better described as 'we need help on each screen' ... :(

**Comment by darcywong00** [comment]
> From Facebook: "You might want to note that the app uses the term "dictionary" whereas all the documentation uses the term "lexical model". Additionally while the Keyman help has an article entitled "How do I remove a dictionary?" It does not have one entitled, "How do I add a dictionary?" If you add such an article, you could mention the need to create a lexical model and provide the link you gave me."

**Comment by jahorton** [comment]
Note that https://github.com/keymanapp/help.keyman.com/pull/315 made tweaks to one of the existing help pages partly to this effect.  ("Installing a keyboard" page now mentions "can also follow these steps for a dictionary".)

**Comment by darcywong00** [comment]
iOS help updated in keymanapp/keyman#4550
