### ISSUE TITLE
Update iOS resource download method docs for 14.0

### ISSUE THREAD

**Issue by jahorton** [keymanapp/help.keyman.com#183]
In reference to https://help.keyman.com/developer/engine/iphone-and-ipad/13.0/Manager/downloadLexicalModel, and probably the keyboard variant too.

The second syntax was only used by the old adhoc model that involved URLs and JSON, predating KMPs, and is being removed.  Instead, use `ResourceFileManager`'s `prepareKMPInstall` method and related to install packages.

**Comment by mcdurdin** [comment]
@jahorton we need to get this documentation update done -- it's been on the back burner for too long 😢

**Comment by jahorton** [comment]
https://help.keyman.com/DEVELOPER/engine/iphone-and-ipad/15.0/KeymanPackage/
https://help.keyman.com/DEVELOPER/engine/iphone-and-ipad/15.0/ResourceFileManager/
https://help.keyman.com/DEVELOPER/engine/iphone-and-ipad/15.0/LanguageResource/

It was done long ago; I just didn't remember the issue itself, most likely, and never closed it.  We can rectify that last point now.
