### ISSUE TITLE
bug: Keyman logo overlaps with a menu when page down

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/help.keyman.com#261]
**Describe the bug**
In Keyman Configuration, go to Support and then scroll down to see more context. You may see on the top right that the Keyman logo overlaps with a menu.

![image](https://user-images.githubusercontent.com/28331388/100406170-d95edd80-3097-11eb-9474-8342f8607e5a.png)

**Expected behavior**
The logo should be where it is, but the menu should be scootered to the right to avoid overlapping with the logo.

---

**Keyman for macOS:**
 - OS: macOS Mojave, 
 - Keyman version: 14.0.190
 - Target Application: Keyman Configuration
 
---

**Additional context**
This similar behavior is seen when browsing [a help page](https://help.keyman.com/?_ga=2.38951403.977768928.1606093069-30305726.1574652282) on a narrower window in Chrome on Windows 10 Pro:
![image](https://user-images.githubusercontent.com/28331388/100406477-86d1f100-3098-11eb-91a4-6c0df6069ca8.png)

**Comment by mcdurdin** [comment]
This issue occurs with the second stop in the responsive sizing:

# 1st step:
![image](https://user-images.githubusercontent.com/4498365/100412434-c9132680-30c8-11eb-8bcf-67eeaf50aec3.png)

# 2nd step:
![image](https://user-images.githubusercontent.com/4498365/100412455-df20e700-30c8-11eb-95cb-c4e82a09470e.png)

# 3rd step:
![image](https://user-images.githubusercontent.com/4498365/100412462-e6e08b80-30c8-11eb-94b5-71e644d9ebec.png)

# 4th step:
![image](https://user-images.githubusercontent.com/4498365/100412468-eba53f80-30c8-11eb-9d22-bbebd9ab9059.png)
