### ISSUE TITLE
chore: Update iOS help for 14.0

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/help.keyman.com#287]
This is a general list of help documentation to update for 14.0 (`staging` branch). We'll have a separate list for each product

- [x] It would be nice to reorganize the hierarchy to match Windows
- [ ] Add guide for installing dictionary per #158  (new content to use Markdown)

**Comment by jahorton** [comment]
> * [ ]  It would be nice to reorganize the hierarchy to match Windows

... isn't that kind of apples & oranges?  Or can you give a more concrete example of what this means?

**Comment by darcywong00** [comment]
I believe @mcdurdin envisions (someday) all the products organize their help along the lines of 

http://help.keyman-staging.com/products/desktop/14.0/docs/

## Table of Contents
1. About Keyman
2. Getting Started
3. Basic Help
4. Advanced Help
5. Common Questions
6. Troubleshooting Index
7. Context Help

**Comment by mcdurdin** [comment]
> I believe @mcdurdin envisions (someday) all the products organize their help along the lines of

Yes, something like this, but you may not need all categories for all projects.

**Comment by darcywong00** [comment]
This is closed since the second point is handled in a separate issue
