### ISSUE TITLE
Version number on 13 is shown as 10

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/help.keyman.com#313]
![Screenshot_20210207-210125_Chrome](https://user-images.githubusercontent.com/28331388/107148781-a97d6180-6987-11eb-84e5-998d741b6d07.png)

Here is the link to the page:

https://help.keyman.com/products/desktop/13.0/docs/about

**Comment by MakaraSok** [comment]
Also here: https://help.keyman.com/developer/engine/desktop/current-version/

**Comment by mcdurdin** [comment]
This is targeted to be fixed in 14.0. See https://help.keyman.com/products/windows/14.0/ :)
