### ISSUE TITLE
Lexical model documentation TODOs

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/help.keyman.com#35]
> I've copied from an [earlier comment](https://github.com/keymanapp/help.keyman.com/pull/32#issuecomment-523264432) the outstanding TODO items:

 - [x] I'll write documentation about how to run the lexical model compiler
 - [ ] I'll move the "advanced model configuration" to somewhere that is NOT the tutorial, as that assumes people know how to write TypeScript code :/

> And from [this comment](https://github.com/keymanapp/help.keyman.com/pull/32#issuecomment-522652848):

 - [x] How do I compile a lexical model?
   - [x] **Blocker**: requires a standalone model compiler keymanapp/keyman#1983, keymanapp/keyman#1986
 - [x] How do I test a lexical model?
 - [x] How do I package a lexical model?
    - [x] **Blocker**: Requires support in Keyman Developer keymanapp/keyman#1977, keymanapp/keyman#2024
 - [x] How do I share my lexical model with Keyman's API? Done: https://help.keyman.com/developer/lexical-models/

_Originally posted by @mcdurdin in https://github.com/keymanapp/help.keyman.com/pull/32#issuecomment-527272735_

**Comment by mcdurdin** [comment]
See #108 for initial seed of testing lexical model and some work on 'advanced', in the reference/file-types/model-ts area. That leaves 'sharing a lexical model' which was done in https://help.keyman.com/developer/lexical-models/

I'll mark #108 as closing this; we could do more but this gets us over the line.
