### ISSUE TITLE
chore: .htaccess update needed

### ISSUE THREAD

**Issue by jahorton** [keymanapp/help.keyman.com#369]
> Extra question - I just went to one of the Markdown-based help pages on my development version to double-check how that would look in comparison. (http://help.keyman.com.local/developer/engine/android/14.0/KeyboardEventHandler/onLexicalModelInstalled)
> 
> Unfortunately, all that nets me is a big ol' "404 Not Found".

Yes, this is because the sites are built on IIS using web.config and you are on (presumably) Apache using .htaccess. We should update the .htaccess files to match the web.config formats. But it's kinda busy-work...

_Originally posted by @mcdurdin in https://github.com/keymanapp/help.keyman.com/issues/367#issuecomment-811572599_

**Comment by darcywong00** [comment]
Relates to keymanapp/keyman.com#337

**Comment by darcywong00** [comment]
FYI @jahorton - #588 fixed most of this on the staging branch. You'll probably need to fiddle 
https://github.com/keymanapp/help.keyman.com/blob/56a4b65005a35388e1c48228c24d4b97fb1f9e09/.htaccess#L4

to match your dev environment (assuming you're hosting the site locally). I haven't finished getting it to run with Docker.

**Comment by darcywong00** [comment]
Marking other TODOs:
* Get links to work with Docker
* Convert the GitHub Action from Windows to Linux

**Comment by darcywong00** [comment]
This is resolved for the staging branch by #588 and all the follow-on PRs. I'll go ahead and close this.
