### ISSUE TITLE
Add a bullet point to the prerequisites

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/help.keyman.com#392]
Nothing about space or word boundary is given at [page](https://help.keyman.com/developer/14.0/guides/lexical-models/tutorial/step-1). Most user would assume that the LM would work regardless.

Proposed bullet point:

* The current lexical model works better with languages that use regular spaces as word boundaries. For complex scripts such as Khmer, Thai, Lao etc, a preprocessing is required before getting it to work, i.e. word segmentation has to be determined and/or configured.

**Comment by jahorton** [comment]
Sounds good.  Maybe reference https://github.com/keymanapp/keyman/issues/5025 as well, as that'd be the feature request addressing the same point.
