### ISSUE TITLE
bug: Version history shows alpha version

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/help.keyman.com#408]
If you try to get to the version history you end up with version history of the current alpha version instead of the released version!

https://help.keyman.com/products/linux/version-history

(This applies to all platforms)

**Comment by mcdurdin** [comment]
Keep scrolling -- stable is shown further down the history?

**Comment by mcdurdin** [comment]
We could improve these pages by having TOC links at the top for stable / alpha.

**Comment by mcdurdin** [comment]
I think this is largely resolved now -- stable history will be automatically merged into HISTORY.md with keymanapp/keyman#7777 and its cherry-picks. With the automatic index on the right hand side of the page, it's good enough :grin:
