### ISSUE TITLE
kmp.inf kmp.jason

### ISSUE THREAD

**Issue by drhemanta** [keymanapp/help.keyman.com#412]
kmp.ihf and kmp.jason files are said to be created automatically with Keyman Developer 14.0 . But we can not see them. Where are they?

**Comment by darcywong00** [comment]
When Keyman Developer creates a keyboard package (.kmp), the kmp.inf and kmp.json files are within the `build\[keyboard].kmp` file.

The .kmp file is just a zip file, so if you unzip it, you'll see those metadata files.

More info on the "Details" section of
https://help.keyman.com/developer/14.0/reference/file-types/metadata
