### ISSUE TITLE
Document fallback behaviour of language tags

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/help.keyman.com#47]
> In the original design, Keyman was supposed to fall back to shorter tags when searching for an appropriate model, e.g. `en-AU` would be searched first, then `en`. This meant that a US English model should have `en-US` and `en` BCP-47 tags assigned. Or, `tpi-Latn-PG -> tpi-Latn -> tpi-PG -> tpi` (i.e. script has heavier weight than region in search). That level of detail probably doesn't belong on this page but does belong somewhere in the docs.

> I'm not sure we ever implemented this? If not, please turn this into an issue :)

_Originally posted by @mcdurdin in https://github.com/keymanapp/help.keyman.com/pull/44_

You, got it, Marc ;)

**Comment by darcywong00** [comment]
Maybe combine this with #14?

**Comment by mcdurdin** [comment]
@darcywong00 Yes please then close this. Also note that NRSI is now WSTech ;-)
