### ISSUE TITLE
docs(android/engine): document `applyKeyboardHeight`

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#489]
> Is this feature available in KMEA? How would I trigger it?

@MattGyverLee - I was originally going to say it's only available in the Keyman for Android 15.0 app. But it turns out there's a new API in Keyman Engine for Android 15.0 you can try:

```
  public static void applyKeyboardHeight(Context context, int height) {
```

where `height` units is dp. see: https://github.com/keymanapp/keyman/blob/892416df8f096285357ef9df9467be1519da48ab/android/KMEA/app/src/main/res/values/dimens.xml#L5

TODO: document on help.keyman.com

_Originally posted by @darcywong00 in https://github.com/keymanapp/keyman/issues/3225#issuecomment-922562678_

**Comment by darcywong00** [comment]
Documentation was resolved in #457.
