### ISSUE TITLE
Two suggestions for the test / keyboard touch and desktop page

### ISSUE THREAD

**Issue by sewhite** [keymanapp/help.keyman.com#491]
1) I was baffled for a while that I could not get my iPhone to find a keyboard I was testing even though my PC and iPhone were on the same network. To get this to work, I needed to turn on network discovery on the PC. This is in Network Sharing Center > Advanced  sharing settings.

![image](https://user-images.githubusercontent.com/16904461/143252508-4116f083-3c9e-4016-b1b8-bbd4e5aba13f.png)

2) In the paragraph that begins "Then you will need to pick an address ...", the reference to a canonical domain name is mysterious to me. I suggest removing this phrase and saying "addresses like ", then give an example or examples from the screenshot of the canonical domain name. 

The page:
https://github.com/keymanapp/help.keyman.com/blob/master/developer/14.0/guides/test/keyboard-touch-and-desktop.php

**Comment by mcdurdin** [comment]
> 1. I was baffled for a while that I could not get my iPhone to find a keyboard I was testing even though my PC and iPhone were on the same network. To get this to work, I needed to turn on network discovery on the PC. This is in Network Sharing Center > Advanced  sharing settings.

I don't recommend this. A Public profile for your wifi, is setup to firewall your computer. Turning on network discovery undoes this, which impacts the safety of your computer on any wifi network you connect to. The better solution is to use a Private profile (e.g. Home or Work) for a trusted network.

**Comment by sewhite** [comment]
Yes, maybe the issue is the wireless network here in my house is labeled public. I can fix that by going to the settings for my network.   SteveWhiteLanguage Technology UseSIL ***@***.***: 704-589-0271O: 704-843-6337Eastern Time (UTC -5:00 / -4:00)  From: Marc DurdinSent: Wednesday, November 24, 2021 4:27 PMTo: keymanapp/help.keyman.comCc: Steve White; AuthorSubject: Re: [keymanapp/help.keyman.com] Two suggestions for the test / keyboard touch and desktop page (Issue #491) I was baffled for a while that I could not get my iPhone to find a keyboard I was testing even though my PC and iPhone were on the same network. To get this to work, I needed to turn on network discovery on the PC. This is in Network Sharing Center > Advanced sharing settings.I don't recommend this. A Public profile for your wifi, is setup to firewall your computer. Turning on network discovery undoes this, which impacts the safety of your computer on any wifi network you connect to. The better solution is to use a Private profile (e.g. Home or Work) for a trusted network.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mcdurdin** [comment]
Work we are completing in Keyman Developer 15 should make it easier to locate the test page by allowing a public URL to access it, so will go ahead and close this issue on that basis. See keymanapp/keyman#6073.
