### ISSUE TITLE
chore: document &CasedKeys does not work with otherwise rule-less keys

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/help.keyman.com#503]
Document the limitation from keymanapp/keyman#4882

> **Describe the bug** &CasedKeys doesn't work with keys that haven't been defined and therefore produce the US English default. (Perhaps this is how it is designed, in which case this should be a feature request!)
> 
> **To Reproduce** I encountered this when reviewing [keymanapp/keyboards#1519](https://github.com/keymanapp/keyboards/pull/1519) and suggesting the author add: `store(&CasedKeys) 'a'..'b' 'd'..'g' 'i'..'p' 'r'..'w' 'y'..'z'` to the keyboard to apply CapsLock logic to keys that were not redefined. When I added the statement, I found I needed to add: `+ 'a' > 'a'` and `+ 'A' > 'A'` to get CapsLock to work with the "a" key.
> 
> **Expected behavior** I expected that putting 'a' in the &CasedKeys store would apply the CapsLock logic to the existing default rules for 'a' and 'A'.
> 
> **Keyman for Windows:**
> 
> * OS: Windows 10 20H2 x64
> * Keyman version: 14.0.271
> 
> **Keyman Developer:**
> 
> * OS: Windows 10 20H2 x64
> * Keyman Developer version: 14.0.271.0

This is "by design" for now.

**Comment by mcdurdin** [comment]
Turns out this was already in place:

```
**Note:** you must define rules for all keys that you list in the `&CasedKeys`
store; casing behavior will not be applied to default outputs from the base
keyboard.
```

https://help.keyman.com/developer/language/reference/casedkeys
