### ISSUE TITLE
"Ask one of the team members to make a manual build of this PR."

### ISSUE THREAD

**Issue by BenArzoun** [keymanapp/help.keyman.com#554]
So, uhh... Do I just wait or? I don't know how to use this site at all.

![image](https://user-images.githubusercontent.com/106128672/169934844-52065110-9045-4c85-9c3d-b9685e7544fd.png)

**Comment by darcywong00** [comment]
You can disregard that. It's just a notification that someone on our team will manually trigger a build to verify your keyboard pull-request can be accepted.
