### ISSUE TITLE
Add sharing file via cloud service as an option for distributing package files to mobile devices

### ISSUE THREAD

**Issue by sewhite** [keymanapp/help.keyman.com#573]
On page https://help.keyman.com/developer/15.0/guides/distribute/packages

Suggest adding this (bold text is addition).

 Once the keyboard package .kmp file is created, you can share them via external storage devices (USB drive, SD card, etc). **You can also share the package file via a cloud storage system (Google Drive, Dropbox or similar service), then share the link to your device via text, note or email. Another** ~~If this is not an~~ option, you can upload the .kmp file to a public facing website. For this example, the keyboard package for Khmer Angkor is being uploaded:

**Comment by mcdurdin** [comment]
@sewhite thank you for the contribution! Note that you can also propose changes directly to the source documentation files by clicking the Edit Page link at the bottom of any page in the documentation site:

![image](https://user-images.githubusercontent.com/4498365/180326868-c4bbb0c0-fb48-42d5-82c4-c42cbd980795.png)
