### ISSUE TITLE
chore: handle folder vs filename conflicts for keyboard assets in .htaccess

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/help.keyman.com#603]
While working on .htaccess redirects as part of keymanapp/help.keyman.com#599
I ran into complications in handling the keyboard help for
https://help.keyman.com/keyboard/khmer_angkor

The full path of the help page is:
http://help.keyman.com/keyboard/khmer_angkor/1.3/khmer_angkor.php

But the .htaccess rules can get confused by the asset folder
https://help.keyman.com/keyboard/khmer_angkor/1.3/khmer_angkor/ (note there's both khmer_angkor.php and the folder khmer_angkor/ with the latter showing permission denied)

Is it possilble to collapse all the khmer_angkor/source/help/khmer_angkor assets up to help/?

**Comment by mcdurdin** [comment]
@darcywong00 is this now resolved in the ongoing docker work?

**Comment by darcywong00** [comment]
It's still a TODO

**Comment by darcywong00** [comment]
> The -f test on line 181 should prevent a redirect. These rules should be handling khmer_angkor.php:
> https://github.com/keymanapp/help.keyman.com/blob/18b127580da48a5a806c5f2061649d0ea417f234/.htaccess#L199-L202
> If that isn't happening, we need a trace of what rules are being applied to prevent it from happening.

This block is now on the following lines
https://github.com/keymanapp/help.keyman.com/blob/e021c0f79eb134da2d5d4d8c7302e895b4fb8b93/.htaccess#L206-L209

When we  "Remove .php extension and redirect", afaict, we don't reach L206 because $1 is now a folder and processing ends here
https://github.com/keymanapp/help.keyman.com/blob/e021c0f79eb134da2d5d4d8c7302e895b4fb8b93/.htaccess#L192-L196

**Comment by mcdurdin** [comment]
> When we "Remove .php extension and redirect", afaict, we don't reach L206 because $1 is now a folder and processing ends here [l. 192-196]

Line 194 should be preventing this from matching.

**Comment by mcdurdin** [comment]
Fixed by #715, `DirectorySlash off`, `[DPI]`, and `"Finally, append the terminating slash for folders"` rule.

Also removing nested .htaccess and adding rules in root simplified the problem.
