### ISSUE TITLE
chore: broken links for three GFF keyboards

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#729]
```
Getting links from: http://localhost:8888/keyboard/gff_tigrinya_eritrea
├─BROKEN─ http://localhost:8888/keyboard/gff_tigrinya_eritrea/2.0/TigrinyaErTyping.pdf (HTTP_404)
--
Getting links from: http://localhost:8888/keyboard/gff_tigre
├─BROKEN─ http://localhost:8888/keyboard/gff_tigre/1.0/TigreTyping.pdf (HTTP_404)
--
Getting links from: http://localhost:8888/keyboard/gff_harari/1.0.1
├─BROKEN─ http://localhost:8888/keyboard/gff_harari/1.0.1/HarariTyping-Harari.pdf (HTTP_404)
```

@dyacob FYI. I'll fix gff_harari 1.0.1 on help.keyman.com, but the other two .php still need updating in the keyboards repo, tracked in keymanapp/keyboards#2254.

**Comment by dyacob** [comment]
Ok, I'll get them in the next few hours. 

Would it be possible to have the php help file import the welcome file as part of its body?  PHP supports this with:

``
<?php echo file_get_contents('URL'); ?>
``

This would reduce the maintenance burden but requires the welcome file to be accessible to the PHP file.

I have in mind revamping all of the GFF help files to make them more uniform.

**Comment by mcdurdin** [comment]
@dyacob I've fixed the .php files in #730, so you will just be able to pull those changes.

Unifying welcome.htm and .php is on our agenda. Difficulties abound with CSS and other headers. Needs substantial further design and discussion...
