### ISSUE TITLE
Move kb content from tavultesoft.com to help.keyman.com

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#76]
- [x] Add a Markdown to HTML preprocessor
- [x] Reformat each KB article as Markdown
- [x] Setup web.config to redirect /kb/xxxx to appropriate /kb/index.php?id=xxxx to load the markdown.
- [x] Setup redirects from tavultesoft.com

**Comment by darcywong00** [comment]
> Add a Markdown to HTML preprocessor

There's [parsedown](https://github.com/erusev/parsedown) which needs composer to install.
They have a [demo](https://parsedown.org/demo) site.
