### ISSUE TITLE
docs: 'testing a keyboard' still talks about old chrome emulation for testing in Dev16

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#786]
We have a server topic https://help.keyman.com/developer/16.0/context/server which covers all the detail about how to test a keyboard in a browser, but the old topic https://help.keyman.com/developer/16.0/guides/test/keyboard-touch-mobile-emulator is still present, which is confusing to users, as it is completely unnecessary to go through the steps in that topic.

**Comment by darcywong00** [comment]
I think this is fixed on `staging` by #803.

**Comment by mcdurdin** [comment]
Fixed on staging
