### ISSUE TITLE
docs(developer): Caps Lock layer section needs improvement

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/help.keyman.com#868]
https://help.keyman.com/developer/language/guide/casing-support#toc-caps-lock-layer

The Caps Lock layer section on this link needs detailed instruction on how to utilize it in touch layout.

Something like this should be helpful.
[Caps Lock layer - mkr.pdf](https://github.com/keymanapp/help.keyman.com/files/13293420/Caps.Lock.layer.-.mkr.pdf)

**Comment by mcdurdin** [comment]
The instructions in the attached PDF are not correct:

1. The shift key should have next layer = default, not caps. The double-tap is automatically enabled on Shift key when the caps layer is present, as the documentation says.
2. The nextlayer information for the Shift layer keys is covered in the very next section of the page:

> In earlier versions of Keyman, it was common to include nextlayer controls on individual output keys (particularly in shift or symbol layers) to return to the previous layer after touching them. In Keyman 15 and later versions, this can be implemented with more control using the [begin PostKeystroke rule](https://help.keyman.com/developer/language/reference/begin).

So, it's better to leave the 'nextlayer' setting on all keys on the Shift and Caps layers as '(none)', and use the rules as shown on that page to control all aspects of the Shift and Caps layer switching.

I'm not sure there is anything else to action here.
