### ISSUE TITLE
Document how to transition from KMFL to Keyman for Linux

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/help.keyman.com#94]
From developer discussion on packaging KMFL vs Keyman for Linux with 20.04 LTS

Question raised:  Are current KMFL users expected to easily migrate to Linux Keyman, or is that not super smooth and people would be easily expected to continue using KMFL for a while?

Given there's current feedback from users that still use KMFL with their .kmn keyboards

@mcdurdin writes
> It might be good to document the transition process from KMFL to Keyman - keyboards, setup and more

Some possible steps:
1. Use kmcomp to compile .kmn to .kmx
2. Use a TBD script to generate a bare .kps package source file (XML) containing the .kmx file.

Considerations:
How to search for .kmn files (user home or system directories?)

**Comment by darcywong00** [comment]
Maybe someone from the Community Site [forum](https://community.software.sil.org/c/keyman) can develop this

**Comment by mcdurdin** [comment]
Do you want to make a request on the forum? I don't think this issue will be all that visible to most people otherwise.

**Comment by darcywong00** [comment]
@ermshiperete provided the following on a Linux-user forum:

> However, I'd recommend switching to ibus-keyman. As you discovered that requires .kmp instead of .kmn files, but it's fairly easy to get to that:
>
>It requires installing Node (version 18.0). On Ubuntu 24.04 this can be installed with:
>
>```
>sudo apt install npm
>```
>(For older Ubuntu versions consult the [nodejs.org](http://nodejs.org/) website how to install node 18)
>
>Then install kmc, the Keyman compiler: `sudo npm install -g @keymanapp/kmc`
>
>Create a new directory for your keyboard (replace "mykeyboard" with the appropriate name...), and a source >subdirectory in that: `mkdir -p mykeyboard/source`
>
>Move your .kmn file to source/mykeyboard.kmn.
>
>Then create two files:
>
>Create a file mykeyboard.kpj:
>```xml
><KeymanDeveloperProject>
>  <Options>
>    <Version>2.0</Version>
>  </Options>
></KeymanDeveloperProject>
>```
>And source/mykeyboard.kps:
>```xml
><Package>
>  <Info>
>    <Name>MyKeyboard</Name>
>  </Info>
>  <Files>
>    <File>
>      <Name>../build/mykeyboard.kmx</Name>
>    </File>
>  </Files>
>  <Keyboards>
>    <Keyboard>
>      <Name>MyKeyboard</Name>
>      <ID>mykeyboard</ID>
>    </Keyboard>
>  </Keyboards>
></Package>
>```
>Build the .kmp file with: `kmc build mykeyboard.kpj`
>
>In the current version (17.0.326) this will fail with `TypeError: Cannot read properties of undefined (reading 'description')`,
>but it will already have created the .kmp file in the build subdirectory. You can install the .kmp file with: 
>`km-package-install -f build/mykeyboard.kmp`
>
>(To properly do this without an error, you'll have to add some additional fields to the .kps file. It's easiest to let the >kmconvert tool generate a template which will contain all necessary fields: `kmconvert template -id mykeyboard`
>Unfortunately this tools isn't available on Linux yet.)
>
>Hope this helps,

**Comment by ermshiperete** [comment]
See also https://github.com/keymanapp/keyman/issues/11857

**Comment by darcywong00** [comment]
Fixed by #1335 in the KB article
