### ISSUE TITLE
feat: support GFM-style alerts in Markdown

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#954]
From #952.

See: https://github.com/orgs/community/discussions/16925

**Comment by mcdurdin** [comment]
This has to be added as a feature to Parsedown, which is the Markdown renderer that we use.

https://github.com/orgs/community/discussions/16925 shows the styles we are aiming for, let's stick with those.

There may be a feature in Parsedown that does this for us, I haven't looked.

**Comment by mcdurdin** [comment]
For reference, this is what we are looking for!

![image](https://github.com/keymanapp/help.keyman.com/assets/4498365/1a2c99b0-20ee-48d9-b0e0-5c8cfea6b4bb)

**Comment by Meng-Heng** [comment]
@mcdurdin, I don't think Parsedown has this feature yet.
- A request for Alerts support: `https://github.com/erusev/parsedown/issues/860`
- Latest Parsedown releases do not mention the Alerts feature: https://github.com/erusev/parsedown/releases
- Other markdown renderers start supporting Alerts upon the User's request: `https://github.com/jgm/commonmark-hs/issues/132`
- Parsedown's demo page:
![image](https://github.com/keymanapp/help.keyman.com/assets/90595388/6b30b78e-22f9-4a45-af63-516431ba4af3)

I also don't see this feature being added to their v2.0.0 roadmap.

**Comment by mcdurdin** [comment]
@Meng-Heng, we'd need to write this as an extension. Parsedown has a tutorial on writing extensions: https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions  

It might be worth reading links https://github.com/erusev/parsedown/issues/860 as well.

If this seems a bit too deep, no worries, we can postpone this and come back to it later

**Comment by Meng-Heng** [comment]
Thank you @mcdurdin,
I have started a composer project on Wednesday so I would like to take a look through the links you sent and see how much I can go from there.

**Comment by Meng-Heng** [comment]
Status Update:
![image](https://github.com/user-attachments/assets/9f867173-76e7-493c-b5e6-4cd7751eba3a)
